# Generated by Django 6.0 on 2025-12-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='E-Shop', help_text='Website name shown in navbar and footer.', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Upload the main logo for the site.', null=True, upload_to='site_logo/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
