# Generated by Django 6.0 on 2025-12-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='steadfast_consignment_id',
            field=models.CharField(blank=True, help_text='Consignment id returned by Steadfast.', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='steadfast_invoice',
            field=models.CharField(blank=True, help_text='Invoice string sent to Steadfast (e.g. ORD-123).', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='steadfast_status',
            field=models.CharField(blank=True, help_text='Latest delivery status from Steadfast.', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='steadfast_tracking_code',
            field=models.CharField(blank=True, help_text='Tracking code returned by Steadfast.', max_length=50),
        ),
    ]
