# Generated by Django 6.0 on 2025-12-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_attribute_attributevalue_productvariant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, help_text='Tick the values for this variant (e.g. 500gm + Red + XL).', related_name='variants', to='shop.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(blank=True, help_text='Optional. If empty, name will be built from attribute values.', max_length=200),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, help_text='Optional SKU/code for this variant.', max_length=100),
        ),
    ]
