# Generated by Django 6.0 on 2025-12-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productvariant_attribute_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fraud_report_data',
            field=models.JSONField(blank=True, help_text='OneCodeSoft API Response Cache', null=True),
        ),
    ]
