# Generated by Django 6.0 on 2025-12-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_fraud_report_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(blank=True, help_text='Short description about your shop for the footer.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, help_text='Office Address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, help_text='Support Email', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook',
            field=models.URLField(blank=True, help_text='Facebook Page URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(blank=True, default='All Rights Reserved.', help_text='Copyright text for the footer.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram',
            field=models.URLField(blank=True, help_text='Instagram Profile URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, help_text='Support Phone Number', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter',
            field=models.URLField(blank=True, help_text='Twitter/X Profile URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube',
            field=models.URLField(blank=True, help_text='YouTube Channel URL'),
        ),
    ]
