# Generated by Django 6.0 on 2025-12-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_deliveryoption_alter_order_delivery_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='steadfast_api_key',
            field=models.CharField(blank=True, help_text='Enter your API Key from Steadfast Merchant Panel', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='steadfast_secret_key',
            field=models.CharField(blank=True, help_text='Enter your Secret Key from Steadfast Merchant Panel', max_length=255),
        ),
    ]
