# Generated by Django 6.0 on 2025-12-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_sitesettings_steadfast_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_access_token',
            field=models.TextField(blank=True, help_text='Long Access Token from Facebook Business Manager (Conversion API)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, help_text='Example: 1234567890', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
