# Generated by Django 6.0 on 2025-12-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_sitesettings_facebook_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_test_event_code',
            field=models.CharField(blank=True, help_text='Only for testing. Example: TEST12345. Leave empty for live orders.', max_length=50),
        ),
    ]
