# Generated by Django 6.0 on 2025-12-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_sitesettings_facebook_test_event_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fbc',
            field=models.CharField(blank=True, help_text='Facebook Click ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fbp',
            field=models.CharField(blank=True, help_text='Facebook Browser ID', max_length=255, null=True),
        ),
    ]
