# Generated by Django 6.0 on 2025-12-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_fbc_order_fbp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Customer IP Address', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Customer Browser User Agent', null=True),
        ),
    ]
