# Generated by Django 6.0 on 2025-12-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_ordernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_pixel_mode',
            field=models.CharField(choices=[('manual', 'Manual (Admin Confirm) - Recommended'), ('automatic', 'Automatic (On Checkout)')], default='manual', help_text='Manual: Send event when Admin confirms order. Automatic: Send event immediately after customer checkout.', max_length=20),
        ),
    ]
