# Generated by Django 6.0 on 2025-12-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_sitesettings_facebook_pixel_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image for this specific variant (e.g., Red Color Image)', null=True, upload_to='products/variants/'),
        ),
    ]
