# Generated by Django 6.0 on 2025-12-29 11:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Or paste YouTube Link (e.g. https://youtu.be/xyz)', null=True),
        ),
        migrations.AlterField(
            model_name='deliveryoption',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryoption',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='fbc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fbp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fraud_report_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text='Upload image OR Video Thumbnail here', upload_to='products/gallery/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file (MP4)', null=True, upload_to='products/videos/'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, help_text='Tick the values for this variant.', related_name='variants', to='shop.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image for this specific variant', null=True, upload_to='products/variants/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_pixel_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_test_event_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='steadfast_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='steadfast_secret_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
