# Generated by Django 6.0 on 2025-12-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_sitesettings_options_productimage_youtube_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryoption',
            name='location',
            field=models.CharField(help_text='e.g. Inside Dhaka, Outside Dhaka', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryoption',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Delivery charge amount', max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_area',
            field=models.CharField(help_text='Selected delivery location name', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='fbc',
            field=models.CharField(blank=True, help_text='Facebook Click ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fbp',
            field=models.CharField(blank=True, help_text='Facebook Browser ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fraud_report_data',
            field=models.JSONField(blank=True, help_text='OneCodeSoft API Response Cache', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Customer IP Address', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Customer Browser User Agent', null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image OR Video Thumbnail here', null=True, upload_to='products/gallery/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_access_token',
            field=models.TextField(blank=True, help_text='Long Access Token from Facebook Business Manager (Conversion API)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, help_text='Example: 1234567890', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_pixel_mode',
            field=models.CharField(choices=[('manual', 'Manual (Admin Confirm) - Recommended'), ('automatic', 'Automatic (On Checkout)')], default='manual', help_text='Manual: Send event when Admin confirms order. Automatic: Send event immediately after customer checkout.', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_test_event_code',
            field=models.CharField(blank=True, help_text='Only for testing. Example: TEST12345. Leave empty for live orders.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='steadfast_api_key',
            field=models.CharField(blank=True, help_text='Enter your API Key from Steadfast Merchant Panel', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='steadfast_secret_key',
            field=models.CharField(blank=True, help_text='Enter your Secret Key from Steadfast Merchant Panel', max_length=255),
        ),
    ]
