# Generated by Django 6.0 on 2026-01-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_category_icon_category_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name_plural': 'Attributes'},
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name_plural': 'Product variants'},
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('color', 'Color'), ('size', 'Size'), ('weight', 'Weight')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='color_code',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deliveryoption',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryoption',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='fbc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fbp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fraud_report_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('sslcommerz', 'SSLCommerz')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_flash_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original/Market Price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling Price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, related_name='variants', to='shop.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/variants/'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_pixel_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_test_event_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='steadfast_api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='steadfast_secret_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
