# Generated by Django 6.0 on 2026-01-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_product_is_flash_sale_alter_product_old_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Attribute', 'verbose_name_plural': 'Attributes'},
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'verbose_name': 'Attribute value', 'verbose_name_plural': 'Attribute values'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'Product variant', 'verbose_name_plural': 'Product variants'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_flash_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('color', 'Color'), ('size', 'Size'), ('weight', 'Weight')], default='text', help_text='Attribute type (text/size/color/weight)', max_length=20),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='color_code',
            field=models.CharField(blank=True, help_text='Only for color attributes (e.g. #FF0000)', max_length=7),
        ),
        migrations.AlterField(
            model_name='deliveryoption',
            name='location',
            field=models.CharField(help_text='e.g. Inside Dhaka, Outside Dhaka', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryoption',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Delivery charge amount', max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_area',
            field=models.CharField(help_text='Selected delivery location name', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='fbc',
            field=models.CharField(blank=True, help_text='Facebook Click ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fbp',
            field=models.CharField(blank=True, help_text='Facebook Browser ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fraud_report_data',
            field=models.JSONField(blank=True, help_text='OneCodeSoft API Response Cache', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Customer IP Address', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('sslcommerz', 'SSLCommerz Online Payment')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Customer Browser User Agent', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image OR Video Thumbnail here', null=True, upload_to='products/gallery/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file (MP4)', null=True, upload_to='products/videos/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Or paste YouTube Link (e.g. https://youtu.be/xyz)', null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='attribute_values',
            field=models.ManyToManyField(blank=True, help_text='Tick the values for this variant.', related_name='variants', to='shop.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image for this specific variant', null=True, upload_to='products/variants/'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(blank=True, help_text='Optional. If empty, name will be built from attribute values.', max_length=200),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty to use main product price.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, help_text='Optional SKU/code for this variant.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_access_token',
            field=models.TextField(blank=True, help_text='Long Access Token from Facebook Business Manager (Conversion API)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, help_text='Example: 1234567890', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_pixel_mode',
            field=models.CharField(choices=[('manual', 'Manual (Admin Confirm) - Recommended'), ('automatic', 'Automatic (On Checkout)')], default='manual', help_text='Manual: Send event when Admin confirms order. Automatic: Send event immediately after customer checkout.', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_test_event_code',
            field=models.CharField(blank=True, help_text='Only for testing. Example: TEST12345. Leave empty for live orders.', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(blank=True, default='All Rights Reserved.', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='steadfast_api_key',
            field=models.CharField(blank=True, help_text='Enter your API Key from Steadfast Merchant Panel', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='steadfast_secret_key',
            field=models.CharField(blank=True, help_text='Enter your Secret Key from Steadfast Merchant Panel', max_length=255),
        ),
    ]
